Repository theforeman/foreman_salt, pull requests merged in 2022-01, with the labels that each got.

#162 Add pagination (again)
  app/views/foreman_salt/salt_autosign/index.html.erb
  app/views/foreman_salt/salt_environments/index.html.erb
  app/views/foreman_salt/salt_keys/index.erb
  app/views/foreman_salt/salt_modules/index.html.erb
Labels: Needs testing, Not yet reviewed

#163 Fixes #34273 - drop usage of require_ssl_smart_proxies
  test/functional/minions_controller_test.rb
Labels: Needs testing, Not yet reviewed

#164 Fix tests because of new pagination method (#162)
  test/integration/salt_autosign_test.rb
  test/integration/salt_keys_test.rb
Labels: Needs testing, Not yet reviewed

#159 Update CI node version to match Foreman 3.2-devel
  .github/workflows/unit_tests.yml
Labels: Needs testing, Not yet reviewed

#165 Remove salt run button on the host page
  app/controllers/foreman_salt/minions_controller.rb
  app/helpers/concerns/foreman_salt/hosts_helper_extensions.rb
  app/models/foreman_salt/concerns/host_managed_extensions.rb
  app/models/setting/salt.rb
  db/migrate/20220118160349_drop_salt_hide_run_salt_button_setting.rb
  test/integration/hosts_js_test.rb
Labels: Needs testing

#138 Fixes #30661 - fix seed order of templates
  db/seeds.d/76-job_templates.rb
Labels: Needs testing, Needs re-review
